version: '3'
services:

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./src:/var/www
    networks:
      - backend-shop-network

  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "8181:80"
      - "443:443"
    networks:
      - backend-shop-network

  db:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_USER=${DB_ROOT_USER}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - './docker/database:/bitnami/mariadb'
    networks:
      - backend-shop-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '1235:80'
    environment:
      - PMA_HOST=db
      - PMA_ROOT_PASSWORD=docker
    links:
      - db:db
    networks:
      - backend-shop-network
    depends_on:
      - db

networks:
  backend-shop-network:
    driver: bridge
